project:
  type: website
  output-dir: docs
  preview:
    port: 4204

title: "MLMC: Machine Learning Monte Carlo"
date: today
date-modified: last-modified
author-title: ""
affiliation-title: ""
published-title: ""
modified-title: ""
title-block-categories: false
number-sections: false
bibliography: references.bib
appendix-cite-as: display
favicon: "./assets/favicon.svg"
twitter-card:
  image: "https://github.com/saforem2/lattice23/blob/main/assets/thumbnail.png?raw=true"
  site: "@saforem2"
  creator: "@saforem2"
author:
  name: Sam Foreman
  url: https://samforeman.me
  orcid: 0000-0002-9981-0876
  email: foremans@anl.gov
  affiliation: Argonne National Laboratory
  affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
citation:
   author: Sam Foreman
   type: speech
   genre: "Presentation at the 2023 International Symposium on Lattice Field Theory"
   container-title: https://indico.fnal.gov/event/57249/contributions/271305/
   title: "MLMC: Machine Learning Monte Carlo for Lattice Gauge Theory"
   url: https://saforem2.github.io/lattice23
   abstract: | 
     We present a trainable framework for efficiently generating gauge
     configurations, and discuss ongoing work in this direction. In particular, we
     consider the problem of sampling configurations from a 4D 𝑆𝑈(3) lattice gauge
     theory, and consider a generalized leapfrog integrator in the molecular
     dynamics update that can be trained to improve sampling efficiency.
  # -----------------------
  # type: article-journal
  # container-title: ACM Transactions on Embedded Computing Systems
  # volume: 21
  # issue: 2
  # issued: 2022-03
  # issn: 1539-9087
  # doi: 10.1145/3514174
  # -----------------------
  # type: speech
  # container-title: "Journal of Data Science Software"
  # doi: "10.23915/reprodocs.00010"
  # url: https://example.com/summarizing-output
  # -----------------------
google-scholar: true
google-analytics: G-XVM2Y822Y1

#
#
#
#
#
# # website:
# #   page-navigation: true
# #   title: "MLMC: Machine Learning Monte Carlo"
# #   # site-url: "https://saforem2.github.io/mlmc"
# #   # favicon: "./assets/favicon.svg"
# appendix-cite-as: display	
# citation:
#    type: speech
#    genre: "Presentation at the 2023 International Symposium on Lattice Field Theory"
#    container-title: https://indico.fnal.gov/event/57249/contributions/271305/
#    title: "MLMC: Machine Learning Monte Carlo for Lattice Gauge Theory"
#    url: https://saforem2.github.io/lattice23
# author:
#   - name: Sam Foreman
#     # id: sf
#     url: https://samforeman.me
#     orcid: 0000-0002-9981-0876
#     email: foremans@anl.gov
#     affiliation: "Argonne National Laboratory"
#     affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
#
#     # affiliation: 
#     #   - name: Argonne National Laboratory
#     #     city: Chicago
#     #     state: IL
#     #     url: https://alcf.anl.gov
#     #
# favicon: "./assets/favicon.svg"
# google-analytics: G-XVM2Y822Y1
# # title: A Published Conference Paper
# # author:
# #   - name: Norah Jones
# #     affiliation: School of Hard Knocks
# #     orcid: 0000-0001-8715-9476
# # citation:
# #   type: paper-conference
# #   container-title: "Proceedings of the annual conference of the Society for Research"
# #   publisher: "Society for Research"
# #   issued: 2020/09/23
# #   volume: 2
# #   doi: "10.23915/reprodocs.00010"
# #   url: https://example.com/summarizing-output
# #   page-first: 46
# #   page-last: 53
# #   editor:
# #   - Don Draper
# #   - Nick Fury
# # google-scholar: true  
# #
# #
# # affiliation: ""
# # date: ""
# # toc: true
# filters:
#   - lua/callouts.lua
# highlight-style:
#   dark: dracula
#   light: dracula-light

